# \>\>\> Assignment 8 {.unnumbered}

1.  Many European policy analysts criticize the European Union and its member states for heavily subsidizing basic research. Instead, they say that applied research should be encouraged to generate competitive advantages for European companies. Explain.

2.  What is the main critique against the WTO with respect to environmental protection? How does the WTO justify its position on trade disputes that involve environmental issues?

3.  There is growing concern that globalization may allow highly polluting industries to move to pollution havens, where regulation is looser. There is little evidence that this is a major factor in actual location decisions, at least so far. But that may change if serious climate-change policies are implemented; in that case, there is a strong case for carbon tariffs, but also strong criticism of the concept. Explain.

You can write your answers and explanations by hand on a paper or use a typewriter such as Microsoft Word on your PCs.

After that, your answers should be sent to the following email address.「trade.moinul\@gmail.com」

Your answer sheets, file and email should be entitled including \`\`Your_student_ID, your name and assignment ID'' such as 1333455_Moinul_Islam_Assignment8.
