# \>\>\> Assignment 1 {.unnumbered}

## Hint:

- Suppose that the two countries are Home and Foreign and the two
goods are Bread and Cloth. The lone factor of production is labor.
The production of one unit of each good in each country requires a
certain amount of labor which is called the unit labor requirement.

- Let's consider:

   -  Home (H)

   -  Foreign (F)

   -  Bread (B)

   -  Cloth (C)

   -  Labor (L)

- We have the following information

   -  In Home, one unit of Labor can produce 1 unit of Bread, H_LB = 1 

   -  In Home, one unit of Labor can produce 2 units of Cloth, H_LC = 2

   -  In Foreign, one unit of Labor can produce 4 units of Bread, F_LB = 4

   -  In Foreign, one unit of Labor can produce 3 units of Cloth, F_LC = 3

- It is easily veriﬁed that Home is better at making both Bread and Cloth because Home requires
less labor to produce a unit of Bread and a unit Cloth compared
to Foreign. 

- In other words, Home labor is more productive than
Foreign in the production of both goods. Thus, Home has an absolute
advantage in the production of both Bread and Cloth.

> Recall that the opportunity cost of producing a good is the next best alternative foregone.

- Home produces one unit of Bread, it uses one unit of labor.
The alternative use of labor in Home is to produce Cloth. How much
Cloth can one unit of labor in Home produce? The answer is 1/2,
because each unit of Cloth requires two units of labor; so, one
unit of labor can produce only 1/2 Cloth. 

Therefore,

- The opportunity cost of producing Bread in Home is 1/2 Cloth

- The ﬂip side of this is that the opportunity cost of producing Cloth in Home is 2 Bread

- For Foreign, the opportunity cost of producing Bread in Foreign is 4/3 Cloth 

- And the opportunity cost of producing Cloth in Foreign is 3/4 Bread


## Assignment 1:

- Suppose the unit labor requirements in Home and Foreign for the two goods Cloth and Wheat are as follows.

- Let's consider:

  - Home (H)

  - Foreign (F)

  - Cloth (C)

  - Wheat (W)

  - Labor (L)

- We have the following data:

  - In Home, one unit of Labor can produce 30 units of Cloth, H_LC = 30

  - In Home, one unit of Labor can produce 20 units of Wheat, H_LW = 20
 
  - In Foreign, one unit of Labor can produce 60 units of Cloth, F_LC = 60

  - In Foreign, one unit of Labor can produce 30 units of Wheat, F_LW = 30


### Answer the following multiple choice questions based on the above.


1) Given the information in the table above, Home has an absolute
advantage in 

A) Cloth
B) Wheat
C) Both Cloth and Wheat
D) Neither


2) Given the information in the table above, the opportunity cost of
Cloth in Home is

A) 1 Wheat
B) 2 Wheat
C) 1.5 Wheat
D) 4 Wheat


3) Given the information in the table above, the opportunity cost of
Wheat in Foreign is

A) 1 Cloth
B) 2 Cloths
C) 1/2Cloth
D) 4 Cloths


4) Which of the following statements is true about the table above?

A) Home has a lower labor productivity in both Cloth and
Wheat.
B) Foreign has a lower labor productivity in both Cloth and
Wheat.
C) Home has a higher labor productivity in cloth, but Foreign
has a higher labor productivity in Wheat.
D) Home has a lower labor productivity in cloth, but Foreign has
a higher labor productivity in Wheat.


5) Which of the following statements is true about the table above?

A) Home has a comparative advantage in both Cloth and Wheat.
B) Foreign has a comparative advantage in both Cloth and
Wheat.
C) Home has a comparative advantage in Cloth and Foreign in
Wheat
D) Foreign has a comparative advantage in Cloth and Home in
Wheat.