# International Trade Models

## The Ricardian model of international trade

-   The Ricardian model of international trade states that the main reason why countries trade is that diﬀerent countries have diﬀerent productivity (or technologies) for producing diﬀerent goods and services.

-   It shows how countries can gain from exporting goods that they are relatively better at making and importing goods that they are relatively worse at making.

### The Ricardian theory

-   The Ricardian theory of comparative advantage is based on the idea that if there are technological diﬀerences in the production of goods across countries,

-   Countries can gain from trade by exporting goods for which the country has a lower opportunity cost of production and importing goods for which the country's opportunity costs of production are higher.

-   The model can be understood using a two-country, two-good and one factor of production example.

-   Suppose that the two countries are Home($h$) and Foreign($f$) and the two goods are Bread ($b$) and Cloth ($c$).

-   The lone factor of production is labor ($L$).

-   The production of one unit of each good in each country requires a certain amount of labor which is called the unit labor requirement.

Let's denote,

-   The unit labor requirement in **`Home`** by $hL_i$
-   The unit labor requirement in **`Foreign`** by $fL_i$
-   Here $i$ = $b$, $c$
    -   $b$ denotes **`Bread`** and $c$ denotes **`Cloth`**

To ﬁx ideas, let us work with the following numbers:

-   $hL_b$ = 1, $hL_c$ = 2, $fL_b$ = 4 and $fL_c$ = 3

## Heckscher--Ohlin model of trade

-   We now go one step further and explain the reason, or cause, for the difference in relative commodity prices and comparative advantage between the two nations.

-   questions were left largely unanswered by Ricardo. According to Ricardo, comparative advantage was based on the difference in the productivity of labor among nations, but he provided no explanation for such a difference in productivity, except for possible differences in climate.

-   The Heckscher--Ohlin model of trade states that endowment diﬀerences among countries play a key role in determining the pattern of trade.

## The Krugman model of trade

-   The Krugman model or the model of trade based on internal economies of scale in production.

-   It shows how countries can gain from trade even in a world where countries have identical endowments and technologies, provided that production functions exhibit increasing returns to scale and consumers have a love for variety.

## The gravity model

-   Let's begin by describing who trades with whom. An empirical relationship known as the gravity model helps to make sense of the value of trade between any pair of countries and sheds light on the impediments that continue to limit international trade even in today's global economy.

-   Three of the top 15 U.S. trading partners are European nations: Germany, the United Kingdom, and France. Why does the United States trade more heavily with these three European countries than with others? The answer is that these are the three largest European economies. That is, they have the highest values of gross domestic product (GDP), which measures the total value of all goods and services produced in an economy.

> There is a strong empirical relationship between the size of a country's economy and the volume of both its imports and its exports.

-   The basic form of the gravity equation is as follows:

$$T_{ij} = \frac{GDP_{i}^{\alpha } GDP_{j}^{\beta}}{D_{ij}^{\theta}}$$
  Here, 
     
  $T_{ij}$ indicates bilateral trade between country $i$, and $j$

  $GDP_i$ indicates the economic size of $i$, measured by gross domestic product  

  $D_{ij}$ indicates the bilateral distance between the two countries 

  The parameters are $α$, $β$, and $θ$
