# The Political Economy of Trade Policy

Previous lectures have answered the question, “Why do nations trade?” by
describing the causes and effects of international trade and the functioning of
a trading world economy. This lecture examines the policies that governments adopt toward international
trade, policies that involve a number of different actions. These actions include:

- Taxes 

- Subsidies 

- Legal limits on the value or volume of particular imports

- Other measures

The chapter thus provides a framework for understanding the effects of the most
important instruments of trade policy.


## Basic Tariff Analysis

A tariff is a tax levied when a good is imported. There are various types of tariff. 

- *Specific tariff* are levied as a fixed charge for each unit of goods imported (for example, $3 per barrel of oil).

- *Ad valorem* tariffs are taxes that are levied as a fraction of the value of
the imported goods (for example, a 25 percent U.S. tariff on imported trucks).

Tariffs are the oldest form of trade policy and have traditionally been used as a source
of government income. Their true purpose is to provide revenue and to protect particular domestic sectors.

The importance of tariffs has declined in modern times because modern governments usually prefer to protect domestic industries
through a variety of non-tariff barriers, such as: 

- Import quotas (limitations on the quantity of imports) 

- Export restraints (limitations on the quantity of exports—usually imposed by the exporting country at the importing country’s request). 

Nonetheless, an understanding of the effects of a tariff remains vital for understanding other trade policies.