# National Income Accounting and the Balance of Payments

### Gross Domestic Product (GDP)

A country's gross domestic product (GDP) is supposed to measure the volume of production within a country's borders, whereas GNP equals GDP plus net receipts of factor income from the rest of the world.

Most countries other than the United States have long reported GDP rather than GNP as their primary measure of national economic activity. In 1991, the United States began to follow this practice as well. As a practical matter, movements in GDP and GNP usually do not differ greatly.

### National Income Accounting for an Open Economy

We will see that in open economies, saving and investment are not necessarily equal, as they are in a closed economy.

-   **Consumption (C)**

The portion of GNP purchased by private households to fulfill current wants is called consumption. Purchases of movie tickets, food, dental work, and washing machines all fall into this category. Consumption expenditure is the largest component of GNP in most economies.

**Example**: In the United States, for example, the fraction of GNP devoted to consumption has fluctuated in a range from about 62 to 70 percent over the past 60 years.

-   **Investment (I)**

The part of output used by private firms to produce future output is called investment. Investment spending may be viewed as the portion of GNP used to increase the nation's stock of capital. Investment is usually more variable than consumption.

**Example**: In the United States, (gross) investment has fluctuated between 11 and 22 percent of GNP in recent years.

-   **Government Purchases (G)**

Any goods and services purchased by federal, state, or local governments are classified as government purchases in the national income accounts. Included in government purchases are federal military spending, government support of cancer research, and government funds spent on highway repair and education. Government purchases include investment as well as consumption purchases.

**Example**: Government purchases currently take up about 17 percent of U.S. GNP, and this share has fallen somewhat since the late 1950s. (The corresponding figure for 1959, for example, was around 22 percent.)

### The National Income Identity for an Open Economy

-   In a closed economy, any final good or service not purchased by households or the government must be used by firms to produce new plant, equipment, and inventories.

-   This information leads to a fundamental identity for closed economies. Let Y stand for GNP, C for consumption, I for investment, and G for government purchases. Since all of a closed economy's output must be consumed, invested, or bought by the government, we can write

$$Y = C + I + G$$

-   Residents of an open economy may spend some of their income on imports, that is, goods and services purchased from abroad, only the portion of their spending not devoted to imports is part of domestic GNP. The value of imports, denoted by IM, must be subtracted from total domestic spending.

-   The goods and services sold to foreigners make up a country's exports. Exports, denoted by EX, are the amount foreign residents' purchases add to the national income of the domestic economy.

-   The national income of an open economy is the sum of domestic and foreign expenditures on the goods and services produced by domestic factors of production. Thus, the national income identity for an open economy is

$$Y = C + I + G + EX - IM$$

## The Current Account (CA)

-   A country's foreign trade is exactly balanced only rarely. The difference between exports of goods and services and imports of goods and services is known as the current account balance (or current account).

-   If we denote the current account by CA, we can express this definition in symbols as:

$$CA = EX - IM$$

-   When a country's imports exceed its exports, we say the country has a *current account deficit*.

-   A country has a *current account surplus* when its exports exceed its imports.

-   The current account is important because it measures the size and direction of international borrowing. When a country imports more than it exports, it is buying more from foreigners than it sells to them and must somehow finance this current account deficit.

### How does country pay for additional imports once it has spent its export earnings?

-   The country as a whole can import more than it exports only if it can borrow the difference from foreigners.

-   A country with a current account deficit must be increasing its net foreign debts by the amount of the deficit.

Example: This is currently the position of the United States, which has a significant current account deficit.

-   A country with a current account surplus is earning more from its exports than it spends on imports. This country finances the current account deficit of its trading partners by lending to them.

-   We have defined the current account as the difference between exports and import . The current account is also equal to the difference between national income and domestic residents' total spending C + I + G:

$$CA = EX-IM$$ $$Y - (C + I + G) = CA$$

## Saving and the Current Account

In a closed economy, national saving always equals investment.

Let S stand for national saving. Our definition of S tells us that $$S = I$$

Since the closed-economy GNP identity, $$Y = C + I + G$$,

may also be written as $$I = Y - C - G$$

Whereas in a closed economy, saving and investment must always be equal, in an open economy they can differ. $$CA = EX - IM$$

we can rewrite the GNP identity as $$S = I + CA$$

Unlike a closed economy, an open economy with profitable investment opportunities does not have to increase its saving in order to exploit them.

Because one country's savings can be borrowed by a second country in order to increase the second country's stock of capital, a country's current account surplus is often referred to as its net foreign investment. Of course, when one country lends to another to finance investment, part of the income generated by the investment in future years must be used to pay back the lender. Domestic investment and foreign investment are two different ways in which a country can use current savings to increase its future income.

## The Balance of Payments Accounts

A country's balance of payments accounts keep track of both its payments to and its receipts from foreigners. Any transaction resulting in a receipt from foreigners is entered in the balance of payments accounts as a credit. Any transaction resulting in a payment to foreigners is entered as a debit. Three types of international transaction are recorded in the balance of payments:

1.  Transactions that arise from the export or import of goods or services and therefore enter directly into the current account.

2.  Transactions that arise from the purchase or sale of financial assets. An asset is any one of the forms in which wealth can be held, such as money, stocks, factories, or government debt. The financial account of the balance of payments records all international purchases or sales of financial assets.

3.  Certain other activities resulting in transfers of wealth between countries are recorded in the capital account. For example, if the U.S. government forgives USD 1 billion in debt owed to it by the government of Pakistan, U.S. wealth declines by USD 1 billion and a USD 1 billion debit is recorded in the U.S. capital account.

## The Fundamental Balance of Payments Identity

Because any international transaction automatically gives rise to offsetting credit and debit entries in the balance of payments, the sum of the current account balance and the capital account balance automatically equals the financial account balance:

$$Currentaccount + Capitalaccount = Financialaccount$$
