# Reasons behind International trade

## Basic reasons behind trade?

-   Countries engage in international trade for two basic reasons
    -   They are different from each other in terms of climate, land, capital, labor, and technology.
    -   They try to achieve scale economies in production.

## Trade Based on Absolute Advantage: Adam Smith

-   The theory of absolute advantage, developed by Adam Smith.

-   Smith started with the simple truth that for two nations to trade with each other voluntarily, both nations must gain. If one nation gained nothing or lost, it would simply refuse to trade. But how does this mutually beneﬁcial trade take place, and from where do these gains from trade come?

-   According to Adam Smith, trade between two nations is based on absolute advantage. When one nation is more efﬁcient than (or has an absolute advantage over) another in the production of one commodity but is less efﬁcient than (or has an absolute disadvantage with respect to) the other nation in producing a second commodity, then both nations can gain by each specializing in the production of the commodity of its absolute advantage and exchanging part of its output with the other nation for the commodity of its absolute disadvantage.

-   By this process, resources are utilized in the most efﬁcient way and the output of both commodities will rise. This increase in the output of both commodities measures the gains from specialization in production available to be divided between the two nations through trade.

-   For example, because of climatic conditions, Canada is efﬁcient in growing wheat but inefﬁcient in growing bananas (hothouses would have to be used). On the other hand, Nicaragua is efﬁcient in growing bananas but inefﬁcient in growing wheat. Thus, Canada has an absolute advantage over Nicaragua in the cultivation of wheat but an absolute dis- advantage in the cultivation of bananas. The opposite is true for Nicaragua.

-   Under these circumstances, both nations would beneﬁt if each specialized in the production of the commodity of its absolute advantage and then traded with the other nation. Canada would specialize in the production of wheat (i.e., produce more than needed domestically) and exchange some of it for (surplus) bananas grown in Nicaragua. As a result, both more wheat and more bananas would be grown and consumed, and both Canada and Nicaragua would gain.

-   Thus, while the mercantilists believed that one nation could gain only at the expense of another nation and advocated strict government control of all economic activity and trade, Adam Smith (and the other classical economists who followed him) believed that all nations would gain from free trade and strongly advocated a policy of `laissez-faire` (i.e., as little government interference with the economic system as possible). Free trade would cause world resources to be utilized most efﬁciently and would maximize world welfare. There were to be only a few exceptions to this policy of laissez-faire and free trade. One of these was the protection of industries important for national defense.

> In view of this belief, it seems paradoxical that today most nations impose many restrictions on the free ﬂow of international trade.

### Example of absolute advantage:

-   one hour of labor time produces six kilograms of wheat in the United States but only one in the United Kingdom.

-   On the other hand, one hour of labor time produces ﬁve units of cloths in the United Kingdom but only four in the United States.

-   Thus, the United States is more efﬁcient than, or has an absolute advantage over, the United Kingdom in the production of wheat, whereas the United Kingdom is more efﬁcient than, or has an absolute advantage over, the United States in the production of cloth.

-   With trade, the United States would specialize in the production of wheat and exchange part of it for British cloth. The opposite is true for the United Kingdom.

Table 3.1: Absolute advantage

|       | USA | UK  |
|-------|-----|-----|
| Wheat | 6   | 1   |
| Cloth | 4   | 5   |

> Absolute advantage, however, can explain only a very small part of world trade today, such as some of the trade between developed and developing countries. Most of world trade, especially trade among developed countries, could not be explained by absolute advantage.

## Trade Based on Comparative Advantage: David Ricardo

-   David Ricardo, writing some 40 years after Smith, to truly explain the pattern of and the gains from trade with his law of comparative advantage.

-   The law of comparative advantage is one of the most important laws of economics, with applicability to nations as well as to individuals and useful for exposing many serious fallacies in apparently logical reasoning.

### The law of comparative advantage

- According to the law of comparative advantage, even if one nation is less efﬁcient than the other nation in the production of both
commodities, there is still a basis for mutually beneﬁcial trade. The ﬁrst nation should
specialize in the production and export of the commodity in which its absolute disadvantage
is smaller (this is the commodity of its comparative advantage) and import the commodity
in which its absolute disadvantage is greater.

- The statement of the law can be clariﬁed by looking at Table 3.2. The only difference
between Tables 3.2 and 3.1 is that the United Kingdom now produces only two units of
cloth per hour instead of ﬁve. Thus, the United Kingdom now has an absolute disadvantage
in the production of both wheat and cloth with respect to the United States.

- However, since U.K. labor is half as productive in cloth but six times less productive in
wheat with respect to the United States, the United Kingdom has a comparative advantage
in cloth.

- On the other hand, the United States has an absolute advantage in both wheat and
cloth with respect to the United Kingdom, but since its absolute advantage is greater in
wheat (6:1) than in cloth (4:2), the United States has a comparative advantage in wheat.

- According to the law of comparative advantage, both nations can
gain if the United States specializes in the production of wheat and exports some of it in
exchange for British cloth. At the same time, the United Kingdom is specializing in the
production and exporting of cloth.

Table 3.2: Comparative advantage

|       | USA | UK  |
|-------|-----|-----|
| Wheat | 6   | 1   |
| Cloth | 4   | 2   |

## Detail analysis of comparative advantage

-   On Valentine's Day the U.S. demand for roses is about 10 million roses.

    -   Growing roses in the U.S. in the winter is difficult. Heated greenhouses should be used. The costs for energy, capital, and labor are substantial.

    -   Resources for the production of roses could be used to produce other goods, say computers.

### Opportunity cost

-   The opportunity cost of roses in terms of computers is the number of computers that could be produced with the same resources as a given number of roses.

### Comparative advantage

-   A country has a comparative advantage in producing a good if the opportunity cost of producing that good in terms of other goods is lower in that country than it is in other countries.

### Gains from trade due to comparative advantage

-   Suppose that in the U.S., 10 million roses can be produced with the same resources as 100,000 computers.

-   Suppose also that in Mexico, 10 million roses can be produced with the same resources as 30,000 computers.

    |        | Millon roses | Thousand computers |
    |--------|--------------|--------------------|
    | U.S    | -10          | +100               |
    | Mexico | +10          | -30                |
    | Total  | 0            | +70                |

## Globalization and international trade

-   Globalization is the process of interaction and integration among people, companies, and governments worldwide.

-   Globalization has accelerated since the 18th century due to advances in transportation and communications technology.

-   This increase in global interactions has caused a growth in international trade.

## The gravity model

-   Let's begin by describing who trades with whom. An empirical relationship known as the gravity model helps to make sense of the value of trade between any pair of countries and sheds light on the impediments that continue to limit international trade even in today's global economy.

-   Three of the top 15 U.S. trading partners are European nations: Germany, the United Kingdom, and France. Why does the United States trade more heavily with these three European countries than with others? The answer is that these are the three largest European economies. That is, they have the highest values of gross domestic product (GDP), which measures the total value of all goods and services produced in an economy.

> There is a strong empirical relationship between the size of a country's economy and the volume of both its imports and its exports.

## Differences between international trade and international finance

::: panel-tabset
### International trade

-   Microeconomics
-   Full employment
-   No savings
-   Balance trade
-   Real transaction

### International finance

-   Macroeconomics
-   Under employment
-   Savings
-   Imbalance trade
-   Monetary transaction
:::
