# Introduction to International Trade

## The gains from trade

-   Probably the most important single insight in all of international economics is that there are gains from trade that is, when countries sell goods and services to each other, this exchange is almost always to their mutual benefit.

-   Although nations generally gain from international trade, it is quite possible that international trade may hurt particular groups within nations---in other words, that international trade will have strong effects on the distribution of income.

> Trade can alter the distribution of income between workers and the owners of capital.

## The pattern of trade

-   Some aspects of the pattern of trade are easy to understand. Climate and resources clearly explain why Brazil exports coffee and Saudi Arabia exports oil.

-   Why does Japan export automobiles, while the United States exports aircraft?

-   There are various different models that try to explain the reason behind the pattern of trade.

> "Who sells what to whom" have been a major question of international economics.

## Determinents of trade

-   After World War II the advanced democracies, led by the United States, pursued a broad policy of removing barriers to international trade; this policy reflected the view that free trade was a force not only for prosperity but also for promoting world peace.

-   In 2016, Britain shocked the political establishment by voting to leave the European Union, which guarantees free movement of goods and people among its members.

> Conflicts of interest within nations are usually more important in determining trade policy than conflicts of interest between nations.

## Balance of payments

-   The balance of payments (BOP) tracks international transactions. When funds go into a country, a credit is added to the balance of payments ("BOP"). When funds leave a country, a deduction is made.

-   The balance of payments includes both the current account and capital/financial account.

    -   The current account (CA) includes a nation's net trade in goods and services, its net earnings on cross-border investments, and its net transfer payments.

    -   The capital/financial account (FA) consists of a nation's transactions in financial instruments and central bank reserves.

    -   The sum of all transactions recorded in the balance of payments should be zero; however, exchange rate fluctuations and differences in accounting practices may hinder this in practice.

> The BOP has become a central issue for the United States because the nation has run huge trade deficits every year since 1982.

## What is trade?

-   Buying and selling goods and services from other countries. Trade consist of imports (M) and exports (X). For instance, in the context of Japan:

    -   The purchase of goods and services from abroad that leads to an outflow of currency from Japan -- Imports (M)
    -   The sale of goods and services to buyers from other countries leading to an inflow of currency to Japan -- Exports (X)

## Basic reasons behind trade?

-   Countries engage in international trade for two basic reasons
    -   They are different from each other in terms of climate, land, capital, labor, and technology.
    -   They try to achieve scale economies in production.

## Trade Based on Absolute Advantage: Adam Smith

- The theory of absolute advantage, developed by Adam Smith. 

- Smith started with the simple truth that for two nations to trade with each other voluntarily,
both nations must gain. If one nation gained nothing or lost, it would simply refuse to trade.
But how does this mutually beneﬁcial trade take place, and from where do these gains from
trade come?

- According to Adam Smith, trade between two nations is based on absolute advantage.
When one nation is more efﬁcient than (or has an absolute advantage over) another in the
production of one commodity but is less efﬁcient than (or has an absolute disadvantage
with respect to) the other nation in producing a second commodity, then both nations can
gain by each specializing in the production of the commodity of its absolute advantage
and exchanging part of its output with the other nation for the commodity of its absolute
disadvantage.

- By this process, resources are utilized in the most efﬁcient way and the output
of both commodities will rise. This increase in the output of both commodities measures
the gains from specialization in production available to be divided between the two nations
through trade.

- For example, because of climatic conditions, Canada is efﬁcient in growing wheat but
inefﬁcient in growing bananas (hothouses would have to be used). On the other hand,
Nicaragua is efﬁcient in growing bananas but inefﬁcient in growing wheat. Thus, Canada
has an absolute advantage over Nicaragua in the cultivation of wheat but an absolute dis-
advantage in the cultivation of bananas. The opposite is true for Nicaragua.

- Under these circumstances, both nations would beneﬁt if each specialized in the production of the commodity of its absolute advantage and then traded with the other nation.
Canada would specialize in the production of wheat (i.e., produce more than needed domestically) and exchange some of it for (surplus) bananas grown in Nicaragua. As a result,
both more wheat and more bananas would be grown and consumed, and both Canada and
Nicaragua would gain.

- Thus, while the mercantilists believed that one nation could gain only at the expense of
another nation and advocated strict government control of all economic activity and trade,
Adam Smith (and the other classical economists who followed him) believed that all nations
would gain from free trade and strongly advocated a policy of `laissez-faire` (i.e., as little
government interference with the economic system as possible). Free trade would cause
world resources to be utilized most efﬁciently and would maximize world welfare. There
were to be only a few exceptions to this policy of laissez-faire and free trade. One of these
was the protection of industries important for national defense.

> In view of this belief, it seems paradoxical that today most nations impose many restrictions on the free ﬂow of international trade.

### Example of absolute advantage:

- one hour of labor time produces six bushels of wheat in the United
States but only one in the United Kingdom. On the other hand, one hour of labor time
produces ﬁve yards of cloth in the United Kingdom but only four in the United States.
Thus, the United States is more efﬁcient than, or has an absolute advantage over, the United Kingdom in the production of wheat, whereas the United Kingdom is more efﬁcient than, or has an absolute advantage over, the United States in the production of cloth. With trade,
the United States would specialize in the production of wheat and exchange part of it for
British cloth. The opposite is true for the United Kingdom.


> Absolute advantage, however, can explain only a very small part of world trade today,
such as some of the trade between developed and developing countries. Most of world trade,
especially trade among developed countries, could not be explained by absolute advantage.

## Trade Based on Comparative Advantage: David Ricardo

- David Ricardo, writing some 40 years after Smith, to truly explain
the pattern of and the gains from trade with his law of comparative advantage. 

- The law of comparative advantage is one of the most important laws of economics,
with applicability to nations as well as to individuals and useful for exposing many
serious fallacies in apparently logical reasoning.

### Example of comparative advantage

-  On Valentine's Day the U.S. demand for roses is about 10 million roses.

    -   Growing roses in the U.S. in the winter is difficult. Heated greenhouses should be used. The costs for energy, capital, and labor are substantial.

    -   Resources for the production of roses could be used to produce other goods, say computers.

### Opportunity cost

-   The opportunity cost of roses in terms of computers is the number of computers that could be produced with the same resources as a given number of roses.

### Comparative advantage

-   A country has a comparative advantage in producing a good if the opportunity cost of producing that good in terms of other goods is lower in that country than it is in other countries.

### Gains from trade due to comparative advantage

-   Suppose that in the U.S., 10 million roses can be produced with the same resources as 100,000 computers.

-   Suppose also that in Mexico, 10 million roses can be produced with the same resources as 30,000 computers.

    |        | Millon roses | Thousand computers |
    |--------|--------------|--------------------|
    | U.S    | -10          | +100               |
    | Mexico | +10          | -30                |
    | Total  | 0            | +70                |

## Globalization and international trade

-   Globalization is the process of interaction and integration among people, companies, and governments worldwide.

-   Globalization has accelerated since the 18th century due to advances in transportation and communications technology.

-   This increase in global interactions has caused a growth in international trade.

## Labor Intensive and capital intensive industries

### What Is labor intensive?

-   The term labor intensive refers to a process or industry that requires a large amount of labor to produce its goods or services.

-   The degree of labor intensity is typically measured in proportion to the amount of capital required to produce the goods or services: the higher the proportion of labor costs required, the more labor-intensive the business.

-   Labor-intensive industries include restaurants, hotels, agriculture, mining, as well as healthcare and caregiver.

-   Less developed economies, as a whole, tend to be more labor-intensive. This situation is rather common because low income means that the economy or business cannot afford to invest in expensive capital.

-   Before the industrial revolution, 90% of the workforce was employed in agriculture. Producing food was very labor-intensive.

### What is capital intensive?

-   Capital intensive refers to the production that requires higher capital investment such as financial resources, sophisticated machinery, more automated machines, the latest equipment, etc.

-   Capital intensive industries pose higher barriers to entry as they require more investment in equipment and machinery to produce goods and services.

-   Good examples of capital intensive industries include the oil refining industry, telecommunications industry, airline industry, and public transport authorities that maintain the roads, railways, trains, trams, etc.

### Differences between capital intensive and labor intensive industries

-   Capital intensive and labor intensive refer to types of production methods followed in the production of goods and services.

-   Capital intensive production requires more equipment and machinery to produce goods; therefore, require a larger financial investment.

-   Labor intensive refers to production that requires a higher labor input to carry out production activities in comparison to the amount of capital required.

**Reference:** Chapter 1- Introduction (Paul Krugman, Maurice Obstfeld, and Marc Melitz, *International Economics*, 12th edition)
