# 国際貿易・国際金融 {.unnumbered}

時間割番号: 1207001101

## 授業の目的 

This course will analyze the causes and consequences of international trade and international finance. After completing this course, you will be able to understand:

1. Why nations trade, what they trade, and who gains (or not) from this trade?

2. The motives for countries or organizations to restrict or regulate international trade and study the effects of such policies on economic welfare.

3. The effects of trade on economic growth and wage inequality, multinationals and foreign direct investment, international trade agreements and current trade policy disputes.

4. International capital flows and their implications for economic policies for individual nations and the world as a whole.

5. Aspects of the current debate on “globalization” such as the use of international labor standards, interactions between trade and environmental concerns, and the role of non-government organizations (NGOs).

Overall, this course will introduce some of the basic concepts of international trade and international finance.

Note: All lecture notes, assignments and quizzes will be available through KUTLMS Moodle.

## 授業の概要  

1. Lecture covers the basics of international trade and international finance.

2. The course will emphasize the understanding of past and current events in the world economy.

3. Lectures will focus on formal economic modeling to help us understand these events.

4. Students will participate in the discussion to express their practical thoughts about trade.

5. The course will introduce recent global issues to make students' understanding realistic and concurrent.

## 到達目標 

The students who succeeded in this course will be able to:

1. Discuss the rationale behind the role of trade

2. Describe the fundamentals of export and import

3. Compare and contrast export and import procedures and strategies

4. Evaluate challenges and opportunities in export and import operations

5. Plan and execute export and import operations

## 授業の方法 

- Lectures are organized as a combination of theories and practices to evaluate the inclusive understanding

- Quizzes and assignments are regularly assigned

## 授業計画  

- 第１回 Basics of International Economics
- 第２回 Introduction to International Trade
- 第３回 Reasons of International Trade
- 第４回 International Trade Models
- 第５回 The Instruments of Trade Policy
- 第６回 The Political Economy of Trade Policy
- 第７回 Trade Policy
- 第８回 Trade Policy in Developing Countries
- 第９回 Globalization, Trade and the Environment
- 第１０回 Macroeconomic Analysis of Trade Balance
- 第１１回 National Income Accounting and the Balance of Payments
- 第１２回 Money, Interest Rates, and Exchange Rates
- 第１３回 Economic Geography
- 第１４回 Developing Countries Growth, Crisis, and Reform
- 第１５回 International Trade and Biodiversity
- 第１６回 Final Examination

## 成績評価の方法・基準 

Attendance, quizzes and assignments account for 50%, and the rest of 50% shall be attributed to the final exam.

AA (Outstanding): Students can effectively operationalize the concepts of human geography, applying them in complex analyses and real-world scenarios.

A (Excellent): Students demonstrate a strong understanding of the concepts of human geography and can draw meaningful implications and interpretations.

B (Good): Students grasp the fundamental concepts of human geography and can apply them to some degree in analysis and interpretation.

C (Fair): Students have a basic understanding of the concepts of human geography and can use them to draw simple conclusions.

F (Failure): Students do not demonstrate an understanding of the fundamental concepts human geography which are necessary for drawing conclusions.

## 授業時間外学習（予習・復習等）

Quizzes and assignments will be assigned regularly for the review of course contents in each lecture.

## キーワード

International trade, international finance, geography, economic development, comparative advantage

## 他の科目との関連 

Introductory microeconomics, introductory macroeconomics

## 備考 

- The medium of instruction is English.

## 教科書

### 教科書1

ISBN	1292409711

書名	International Economics: Theory and Policy

著者名	Krugman, Paul, Maurice Obstfeld, and Marc Melitz	出版社	Pearson Education Limited	出版年	2022

## 参考書

